name: SampleProject
description: Example Power BI Composer project showcasing all pbt features
compatibility_level: 1600
assets:
  project:
    - path: "."
expressions:
  - name: ServerName
    kind: M
    expression: '"localhost" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]'
    description: Database server name parameter
